build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"
      
init:
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: python --version
  - cmd: pip --version
  - cmd: pip install pycodestyle python-docx cx_Freeze

test_script:
  - cmd: pycodestyle . --exclude=backend/data_xml.py

build_script:
  - cmd: python setup.py build

artifacts:
  - path: build/exe.win32-3.6
    name: alinka
    type: zip
